<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet ekr_test?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5">
	<global_window_position top="20" left="20" height="600" width="800"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="tibi.20100526230446.1233" str_leo_pos="1,2"><vh>@chapters</vh></v>
<v t="tibi.20100526230042.1225" a="E"><vh>a node here</vh>
<v t="tibi.20100526230042.1227"><vh>a child</vh></v>
<v t="tibi.20100526230042.1228"><vh>accent: É ü</vh></v>
<v t="tibi.20100526230446.1234"><vh>Chinese: 婷州</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="tibi.20100526230042.1225"></t>
<t tx="tibi.20100526230042.1227">with some text content</t>
<t tx="tibi.20100526230042.1228">été
Übersetzung

</t>
<t tx="tibi.20100526230446.1233"></t>
<t tx="tibi.20100526230446.1234">Chinese: 婷州
</t>
</tnodes>
</leo_file>
